const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const Scholarship = require('../models/Scholarship');

dotenv.config({ path: path.join(__dirname, '../.env') });

const seedScholarshipsData = [
  {
    name: 'Pre-Matric Scholarship for SC Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: '₹225-750/month + book grant',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Caste Certificate', 'Income Certificate', 'Bonafide Certificate', 'Aadhaar Card', 'Bank Passbook'],
    eligibilityRules: {
      minClass: '1st',
      maxClass: '10th',
      maxIncome: null,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Pre-Matric Scholarship for ST Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: '₹225-750/month + book grant',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Caste Certificate', 'Income Certificate', 'Bonafide Certificate', 'Aadhaar Card', 'Bank Passbook'],
    eligibilityRules: {
      minClass: '1st',
      maxClass: '10th',
      maxIncome: null,
      categories: ['ST'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Pre-Matric Scholarship for Minorities',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-15'),
    deadline: new Date('2026-11-15'),
    renewable: true,
    awardAmount: '₹1,000-10,000/year',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Minority Community Certificate', 'Income Certificate', 'Bonafide Certificate', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: '1st',
      maxClass: '10th',
      maxIncome: 100000,
      categories: ['Minority'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Post-Matric Scholarship for SC/ST/OBC Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-05-01'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: '₹1,000-20,000/year (varies by course)',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Caste Certificate', 'Income Certificate', 'Previous Marksheet', 'Bonafide Certificate', 'Bank Passbook', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: '11th',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['SC', 'ST', 'OBC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'National Means-cum-Merit Scholarship (NMMSS)',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-10-15'),
    renewable: true,
    awardAmount: '₹12,000/year',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Income Certificate', 'Previous Marksheet (min 55%)', 'Bonafide Certificate', 'Bank Passbook'],
    eligibilityRules: {
      minClass: '9th',
      maxClass: '12th',
      maxIncome: 350000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: true,
  },
  {
    name: 'Central Sector Scheme of Scholarships for College Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-15'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: '₹12,000/year (UG), ₹20,000/year (PG)',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Class 12 Marksheet (min 80th percentile)', 'Income Certificate', 'Bonafide Certificate', 'Bank Passbook', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: 450000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: true,
  },
  {
    name: 'PM Young Achievers Scholarship (Vibrant India Scheme)',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-05-15'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: '₹75,000/year (residential), ₹25,000/year (day scholar)',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['OBC Certificate', 'Income Certificate', 'Previous Marksheet', 'Bonafide Certificate'],
    eligibilityRules: {
      minClass: '9th',
      maxClass: '12th',
      maxIncome: 250000,
      categories: ['OBC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Top Class Education Scheme for SC Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-12-15'),
    renewable: true,
    awardAmount: 'Full tuition + maintenance allowance',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Caste Certificate', 'Income Certificate', 'Admission Proof (notified institution)', 'Bank Passbook'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'PG',
      maxIncome: 800000,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: true,
  },
  {
    name: 'AICTE Pragati Scholarship for Girls',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-15'),
    deadline: new Date('2026-11-15'),
    renewable: true,
    awardAmount: '₹50,000/year',
    applicationLink: 'https://www.aicte-pragati-saksham-gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Income Certificate', 'Admission Proof (AICTE approved institution)', 'Aadhaar Card', 'Bank Passbook'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: 800000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['Female'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'AICTE Saksham Scholarship for Differently-Abled Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-15'),
    deadline: new Date('2026-11-15'),
    renewable: true,
    awardAmount: '₹50,000/year',
    applicationLink: 'https://www.aicte-pragati-saksham-gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Disability Certificate (min 40%)', 'Income Certificate', 'Admission Proof', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: 800000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: true,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Maulana Azad National Fellowship',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-05-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: 'Monthly stipend (MPhil/PhD rates)',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Minority Certificate', 'NET/JRF or Admission Proof', 'Bonafide Certificate'],
    eligibilityRules: {
      minClass: 'PG',
      maxClass: 'PG',
      maxIncome: null,
      categories: ['Minority'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'National Fellowship for SC Students (UGC)',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-05-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: 'Monthly stipend for MPhil/PhD',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Caste Certificate', 'NET/JRF Qualification or Admission Proof', 'Bonafide Certificate'],
    eligibilityRules: {
      minClass: 'PG',
      maxClass: 'PG',
      maxIncome: null,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'PM Scholarship Scheme for Wards of Ex-Servicemen',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: '₹2,500-3,000/month',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Ex-Servicemen Certificate', 'Admission Proof', 'Bank Passbook'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'PG',
      maxIncome: null,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Single Girl Child Scholarship (CBSE)',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-01'),
    deadline: new Date('2026-12-15'),
    renewable: true,
    awardAmount: '₹500/month (₹6,000/year)',
    applicationLink: 'https://www.cbse.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Single Girl Child Certificate from School', 'Class 12 Marksheet', 'Bank Passbook'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: null,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['Female'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Merit-cum-Means Scholarship for Professional Courses',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-15'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: 'Course fee (up to ₹20,000) + maintenance allowance',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Minority Certificate', 'Income Certificate', 'Admission Proof (professional/technical course)', 'Bank Passbook'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['Minority'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
];

const seedDatabase = async () => {
  try {
    const connStr = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/scholarconnect';
    console.log(`Connecting to MongoDB at ${connStr}...`);
    await mongoose.connect(connStr);

    console.log('Clearing existing placeholder scholarships collection...');
    await Scholarship.deleteMany({});

    console.log('Seeding 15 verified real Indian government scholarships...');
    const inserted = await Scholarship.insertMany(seedScholarshipsData);

    console.log(`✅ Successfully seeded ${inserted.length} real scholarships into ScholarConnect database!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding scholarships:', error);
    process.exit(1);
  }
};

seedDatabase();
