const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const Scholarship = require('../models/Scholarship');

dotenv.config({ path: path.join(__dirname, '../.env') });

const seedScholarshipsData = [
  {
    name: 'Pre-Matric Scholarship for SC Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: '₹225-750/month + book grant',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Caste Certificate', 'Income Certificate', 'Bonafide Certificate', 'Aadhaar Card', 'Bank Passbook'],
    eligibilityRules: {
      minClass: '1st',
      maxClass: '10th',
      maxIncome: null,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Pre-Matric Scholarship for ST Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: '₹225-750/month + book grant',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Caste Certificate', 'Income Certificate', 'Bonafide Certificate', 'Aadhaar Card', 'Bank Passbook'],
    eligibilityRules: {
      minClass: '1st',
      maxClass: '10th',
      maxIncome: null,
      categories: ['ST'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Pre-Matric Scholarship for Minorities',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-15'),
    deadline: new Date('2026-11-15'),
    renewable: true,
    awardAmount: '₹1,000-10,000/year',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://scholarships.gov.in',
    documentsRequired: ['Minority Community Certificate', 'Income Certificate', 'Bonafide Certificate', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: '1st',
      maxClass: '10th',
      maxIncome: 100000,
      categories: ['Minority'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date(),
    featured: false,
  },
  {
    name: 'Post-Matric Scholarship for SC/ST/OBC Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    name: {
      en: 'Pre-Matric Scholarship for SC Students',
      hi: 'अनुसूचित जाति (SC) छात्रों के लिए पूर्व-मैट्रिक छात्रवृत्ति',
      kn: 'ಪರಿಶಿಷ್ಟ ಜಾತಿ (SC) ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಮೆಟ್ರಿಕ್ ಪೂರ್ವ ಸ್ಕಾಲರ್‌ಶಿಪ್',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: {
      en: '₹225-750/month + book grant',
      hi: '₹225-750/माह + पुस्तक अनुदान',
      kn: '₹225-750/ತಿಂಗಳು + ಪುಸ್ತಕ ಅನುದಾನ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://socialjustice.gov.in',
    documentsRequired: [
      { en: 'Caste Certificate', hi: 'जाति प्रमाण पत्र', kn: 'ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Income Certificate', hi: 'आय प्रमाण पत्र', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Aadhaar Card', hi: 'आधार कार्ड', kn: 'ಆಧಾರ್ ಕಾರ್ಡ್' },
      { en: 'Previous Class Marksheet', hi: 'पिछली कक्षा का अंक पत्र', kn: 'ಹಿಂದಿನ ತರಗತಿಯ ಅಂಕಪಟ್ಟಿ' },
      { en: 'Bank Passbook', hi: 'बैंक पासबुक', kn: 'ಬ್ಯಾಂಕ್ ಪಾಸ್‌ಬುಕ್' },
    ],
    eligibilityRules: {
      minClass: '1st',
      maxClass: '10th',
      maxIncome: 250000,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: true,
  },
  {
    name: {
      en: 'Post-Matric Scholarship for SC Students',
      hi: 'अनुसूचित जाति (SC) छात्रों के लिए उत्तर-मैट्रिक छात्रवृत्ति',
      kn: 'ಪರಿಶಿಷ್ಟ ಜಾತಿ (SC) ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಮೆಟ್ರಿಕ್ ನಂತರದ ಸ್ಕಾಲರ್‌ಶಿಪ್',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-01'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: {
      en: '100% Tuition Fee + Maintenance Allowance',
      hi: '100% शिक्षण शुल्क + रख-रखाव भत्ता',
      kn: '100% ಟ್ಯೂಷನ್ ಶುಲ್ಕ + ನಿರ್ವಹಣಾ ಭತ್ಯೆ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://socialjustice.gov.in',
    documentsRequired: [
      { en: 'Caste Certificate', hi: 'जाति प्रमाण पत्र', kn: 'ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Income Certificate', hi: 'आय प्रमाण पत्र', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Aadhaar Card', hi: 'आधार कार्ड', kn: 'ಆಧಾರ್ ಕಾರ್ಡ್' },
      { en: '10th/12th Marksheet', hi: '10वीं/12वीं का अंक पत्र', kn: '10 ನೇ/12 ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ' },
      { en: 'College Fee Receipt', hi: 'कॉलेज शुल्क रसीद', kn: 'ಕಾಲೇಜು ಶುಲ್ಕ ರಸೀದಿ' },
      { en: 'Bonafide Student Certificate', hi: 'बोनाफाइड छात्र प्रमाण पत्र', kn: 'ಬೋನಾಫೈಡ್ ವಿದ್ಯಾರ್ಥಿ ಪ್ರಮಾಣಪತ್ರ' },
    ],
    eligibilityRules: {
      minClass: '11th',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: true,
  },
  {
    name: {
      en: 'National Means-cum-Merit Scholarship Scheme (NMMSS)',
      hi: 'राष्ट्रीय साधन-सह-योग्यता छात्रवृत्ति योजना (NMMSS)',
      kn: 'ರಾಷ್ಟ್ರೀಯ ಮೀನ್ಸ್-ಕಮ್-ಮೆರಿಟ್ ಸ್ಕಾಲರ್‌ಶಿಪ್ ಯೋಜನೆ (NMMSS)',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-15'),
    deadline: new Date('2026-10-15'),
    renewable: true,
    awardAmount: {
      en: '₹12,000/year (₹1,000/month)',
      hi: '₹12,000/वर्ष (₹1,000/माह)',
      kn: '₹12,000/ವರ್ಷ (₹1,000/ತಿಂಗಳಿಗೆ)',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://dsel.education.gov.in',
    documentsRequired: [
      { en: 'Class 7 Marksheet (Min 55%)', hi: 'कक्षा 7 का अंक पत्र (न्यूनतम 55%)', kn: '7 ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ (ಕನಿಷ್ಠ 55%)' },
      { en: 'Income Certificate', hi: 'आय प्रमाण पत्र', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Caste Certificate (if applicable)', hi: 'जाति प्रमाण पत्र (यदि लागू हो)', kn: 'ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ (ಅನ್ವಯಿಸಿದರೆ)' },
      { en: 'Disability Certificate (if applicable)', hi: 'दिव्यांगता प्रमाण पत्र (यदि लागू हो)', kn: 'ವಿಕಲಚೇತನ ಪ್ರಮಾಣಪತ್ರ (ಅನ್ವಯಿಸಿದರೆ)' },
    ],
    eligibilityRules: {
      minClass: '8th',
      maxClass: '12th',
      maxIncome: 350000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'Central Sector Scheme of Scholarships for College and University Students',
      hi: 'कॉलेज और विश्वविद्यालय के छात्रों के लिए केंद्रीय क्षेत्र छात्रवृत्ति योजना',
      kn: 'ಕಾಲೇಜು ಮತ್ತು ವಿಶ್ವವಿದ್ಯಾಲಯ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಕೇಂದ್ರ ವಲಯದ ಸ್ಕಾಲರ್‌ಶಿಪ್ ಯೋಜನೆ',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-15'),
    deadline: new Date('2026-11-15'),
    renewable: true,
    awardAmount: {
      en: '₹12,000/year for Graduation, ₹20,000/year for Post-Graduation',
      hi: 'स्नातक के लिए ₹12,000/वर्ष, स्नातकोत्तर के लिए ₹20,000/वर्ष',
      kn: 'ಪದವಿಗೆ ₹12,000/ವರ್ಷ, ಸ್ನಾತಕೋತ್ತರ ಪದವಿಗೆ ₹20,000/ವರ್ಷ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://www.education.gov.in',
    documentsRequired: [
      { en: '12th Board Marksheet (Top 20th percentile)', hi: '12वीं बोर्ड का अंक पत्र (शीर्ष 20वें पर्सेंटाइल)', kn: '12 ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ (ಟಾಪ್ 20 ಶೇಕಡಾವಾರು)' },
      { en: 'Income Certificate', hi: 'आय प्रमाण पत्र', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Aadhaar Card', hi: 'आधार कार्ड', kn: 'ಆಧಾರ್ ಕಾರ್ಡ್' },
      { en: 'College Admission Proof', hi: 'कॉलेज प्रवेश प्रमाण', kn: 'ಕಾಲೇಜು ಪ್ರವೇಶ ಪ್ರಮಾಣಪತ್ರ' },
    ],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'PG',
      maxIncome: 450000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'PM Young Achievers Scholarship Award Scheme for Vibrant India (PM YASASVI)',
      hi: 'पीएम यशस्वी छात्रवृत्ति योजना (PM YASASVI)',
      kn: 'ಪಿಎಂ ಯಶಸ್ವಿ ಸ್ಕಾಲರ್‌ಶಿಪ್ ಯೋಜನೆ (PM YASASVI)',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-06-01'),
    deadline: new Date('2026-09-30'),
    renewable: true,
    awardAmount: {
      en: '₹75,000/year (Class 9-10), ₹1,25,000/year (Class 11-12)',
      hi: '₹75,000/वर्ष (कक्षा 9-10), ₹1,25,000/वर्ष (कक्षा 11-12)',
      kn: '₹75,000/ವರ್ಷ (9-10 ನೇ ತರಗತಿ), ₹1,25,000/ವರ್ಷ (11-12 ನೇ ತರಗತಿ)',
    },
    applicationLink: 'https://yet.nta.ac.in',
    sourceVerifiedLink: 'https://socialjustice.gov.in',
    documentsRequired: [
      { en: 'YASASVI Entrance Test Scorecard / School Merit Record', hi: 'यशस्वी प्रवेश परीक्षा स्कोरकार्ड / स्कूल मेरिट रिकॉर्ड', kn: 'ಯಶಸ್ವಿ ಪ್ರವೇಶ ಪರೀಕ್ಷೆಯ ಅಂಕಪಟ್ಟಿ / ಶಾಲಾ ಮೆರಿಟ್ ದಾಖಲೆ' },
      { en: 'OBC/EBC/DNT Category Certificate', hi: 'OBC/EBC/DNT श्रेणी प्रमाण पत्र', kn: 'OBC/EBC/DNT ಪ್ರವರ್ಗ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Income Certificate (< ₹2.5 Lakh)', hi: 'आय प्रमाण पत्र (< ₹2.5 लाख)', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (< ₹2.5 ಲಕ್ಷ)' },
      { en: 'Aadhaar Card', hi: 'आधार कार्ड', kn: 'ಆಧಾರ್ ಕಾರ್ಡ್' },
    ],
    eligibilityRules: {
      minClass: '9th',
      maxClass: '12th',
      maxIncome: 250000,
      categories: ['OBC', 'EWS'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'Top Class Education Scheme for SC Students',
      hi: 'अनुसूचित जाति के छात्रों के लिए टॉप क्लास शिक्षा योजना',
      kn: 'ಪರಿಶಿಷ್ಟ ಜಾತಿ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಟಾಪ್ ಕ್ಲಾಸ್ ಶಿಕ್ಷಣ ಯೋಜನೆ',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: {
      en: 'Full Tuition Fee + ₹86,000 first year living & computer allowance',
      hi: 'पूरा शिक्षण शुल्क + ₹86,000 प्रथम वर्ष रहने का और कंप्यूटर भत्ता',
      kn: 'ಸಂಪೂರ್ಣ ಟ್ಯೂಷನ್ ಶುಲ್ಕ + ₹86,000 ಮೊದಲ ವರ್ಷದ ಜೀವನ ಹಾಗೂ ಕಂಪ್ಯೂಟರ್ ಅನುದಾನ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://socialjustice.gov.in',
    documentsRequired: [
      { en: 'Admission Offer Letter from Premier Institute (IIT/NIT/IIM/AIIMS)', hi: 'प्रमुख संस्थान (IIT/NIT/IIM/AIIMS) से प्रवेश पत्र', kn: 'ಪ್ರಮುಖ ಸಂಸ್ಥೆಯಿಂದ (IIT/NIT/IIM/AIIMS) ಪ್ರವೇಶ ಪತ್ರ' },
      { en: 'Caste Certificate', hi: 'जाति प्रमाण पत्र', kn: 'ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Income Certificate (< ₹8 Lakh)', hi: 'आय प्रमाण पत्र (< ₹8 लाख)', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (< ₹8 ಲಕ್ಷ)' },
      { en: 'Fee Structure Breakdown', hi: 'शुल्क संरचना विवरण', kn: 'ಶುಲ್ಕ ವಿವರಣೆ' },
    ],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'PG',
      maxIncome: 800000,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'AICTE Pragati Scholarship for Girl Students (Technical Degree/Diploma)',
      hi: 'छात्राओं के लिए एआईसीटीई प्रगति छात्रवृत्ति योजना',
      kn: 'ಹೆಣ್ಣು ಮಕ್ಕಳಿಗಾಗಿ AICTE ಪ್ರಗತಿ ಸ್ಕಾಲರ್‌ಶಿಪ್ ಯೋಜನೆ',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-08-01'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: {
      en: '₹50,000/year for entire duration of course',
      hi: 'पाठ्यक्रम की पूरी अवधि के लिए ₹50,000/वर्ष',
      kn: 'ಕೋರ್ಸಿನ ಪೂರ್ಣ ಅವಧಿಗೆ ₹50,000/ವರ್ಷ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://www.aicte-india.org',
    documentsRequired: [
      { en: '10th/12th Marksheet', hi: '10वीं/12वीं का अंक पत्र', kn: '10 ನೇ/12 ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ' },
      { en: 'AICTE Approved College Admission Letter', hi: 'एआईसीटीई स्वीकृत कॉलेज प्रवेश पत्र', kn: 'AICTE ಮಾನ್ಯತೆ ಪಡೆದ ಕಾಲೇಜು ಪ್ರವೇಶ ಪತ್ರ' },
      { en: 'Family Income Certificate (< ₹8 Lakh)', hi: 'पारिवारिक आय प्रमाण पत्र (< ₹8 लाख)', kn: 'ಕುಟುಂಬದ ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (< ₹8 ಲಕ್ಷ)' },
      { en: 'Aadhaar Card', hi: 'आधार कार्ड', kn: 'ಆಧಾರ್ ಕಾರ್ಡ್' },
      { en: 'Declaration Form for Single/Two Girl Children', hi: 'एक/दो बालिका संतान घोषणा पत्र', kn: 'ಏಕೈಕ/ಇಬ್ಬರು ಹೆಣ್ಣು ಮಕ್ಕಳ ಘೋಷಣಾಪತ್ರ' },
    ],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: 800000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['Female'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: true,
  },
  {
    name: {
      en: 'AICTE Saksham Scholarship for Specially-Abled Students',
      hi: 'दिव्यांग छात्रों के लिए एआईसीटीई सक्षम छात्रवृत्ति योजना',
      kn: 'ವಿಶೇಷ ಚೇತನ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ AICTE ಸಕ್ಷಮ್ ಸ್ಕಾಲರ್‌ಶಿಪ್',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-08-01'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: {
      en: '₹50,000/year for entire duration of course',
      hi: 'पाठ्यक्रम की पूरी अवधि के लिए ₹50,000/वर्ष',
      kn: 'ಕೋರ್ಸಿನ ಪೂರ್ಣ ಅವಧಿಗೆ ₹50,000/ವರ್ಷ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://www.aicte-india.org',
    documentsRequired: [
      { en: 'Disability Certificate (Min 40% disability)', hi: 'दिव्यांगता प्रमाण पत्र (न्यूनतम 40% दिव्यांगता)', kn: 'ವಿಕಲಚೇತನ ಪ್ರಮಾಣಪತ್ರ (ಕನಿಷ್ಠ 40% ವೈಕಲ್ಯ)' },
      { en: 'AICTE Approved College Admission Letter', hi: 'एआईसीटीई स्वीकृत कॉलेज प्रवेश पत्र', kn: 'AICTE ಮಾನ್ಯತೆ ಪಡೆದ ಕಾಲೇಜು ಪ್ರವೇಶ ಪತ್ರ' },
      { en: 'Income Certificate (< ₹8 Lakh)', hi: 'आय प्रमाण पत्र (< ₹8 लाख)', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (< ₹8 ಲಕ್ಷ)' },
      { en: '10th/12th Marksheet', hi: '10वीं/12वीं का अंक पत्र', kn: '10 ನೇ/12 ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ' },
    ],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: 800000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: true,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'Maulana Azad National Fellowship for Minority Students (MANF)',
      hi: 'अल्पसंख्यक छात्रों के लिए मौलाना आजाद नेशनल फेलोशिप (MANF)',
      kn: 'ಅಲ್ಪಸಂಖ್ಯಾತ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಮೌಲಾನಾ ಆಜಾದ್ ನ್ಯಾಷನಲ್ ಫೆಲೋಶಿಪ್',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: {
      en: '₹31,000/month (JRF) to ₹35,000/month (SRF) + HRA & Contingency',
      hi: '₹31,000/माह (JRF) से ₹35,000/माह (SRF) + एचआरए व आकस्मिकता',
      kn: '₹31,000/ತಿಂಗಳು (JRF) ರಿಂದ ₹35,000/ತಿಂಗಳು (SRF) + HRA ಹಾಗೂ ಅನುದಾನ',
    },
    applicationLink: 'https://minorityaffairs.gov.in',
    sourceVerifiedLink: 'https://ugcnet.nta.nic.in',
    documentsRequired: [
      { en: 'Minority Community Certificate', hi: 'अल्पसंख्यक समुदाय प्रमाण पत्र', kn: 'ಅಲ್ಪಸಂಖ್ಯಾತ ಸಮುದಾಯ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Post-Graduation Marksheet (Min 55%)', hi: 'स्नातकोत्तर का अंक पत्र (न्यूनतम 55%)', kn: 'ಸ್ನಾತಕೋತ್ತರ ಅಂಕಪಟ್ಟಿ (ಕನಿಷ್ಠ 55%)' },
      { en: 'Ph.D./M.Phil. Admission Proof', hi: 'पीएचडी/एम.फिल. प्रवेश प्रमाण पत्र', kn: 'ಪಿಎಚ್.ಡಿ/ಎಂ.ಫಿಲ್ ಪ್ರವೇಶ ಪತ್ರ' },
      { en: 'UGC-NET / CSIR-NET Qualification Proof', hi: 'यूजीसी-नेट / सीएसआईआर-नेट योग्यता प्रमाण', kn: 'UGC-NET / CSIR-NET ಅರ್ಹತಾ ಪ್ರಮಾಣಪತ್ರ' },
    ],
    eligibilityRules: {
      minClass: 'PG',
      maxClass: 'PG',
      maxIncome: 600000,
      categories: ['Minority'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'National Fellowship for SC Students (NFSC)',
      hi: 'अनुसूचित जाति के छात्रों के लिए राष्ट्रीय फेलोशिप (NFSC)',
      kn: 'ಪರಿಶಿಷ್ಟ ಜಾತಿ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ರಾಷ್ಟ್ರೀಯ ಫೆಲೋಶಿಪ್ (NFSC)',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: {
      en: '₹31,000/month (JRF) to ₹35,000/month (SRF) + Contingency',
      hi: '₹31,000/माह (JRF) से ₹35,000/माह (SRF) + आकस्मिकता भत्ता',
      kn: '₹31,000/ತಿಂಗಳು (JRF) ರಿಂದ ₹35,000/ತಿಂಗಳು (SRF) + ಅನುದಾನ',
    },
    applicationLink: 'https://socialjustice.gov.in',
    sourceVerifiedLink: 'https://ugcnet.nta.nic.in',
    documentsRequired: [
      { en: 'SC Caste Certificate', hi: 'अनुसूचित जाति प्रमाण पत्र', kn: 'ಪರಿಶಿಷ್ಟ ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Post-Graduation Marksheet (Min 55%)', hi: 'स्नातकोत्तर का अंक पत्र (न्यूनतम 55%)', kn: 'ಸ್ನಾತಕೋತ್ತರ ಅಂಕಪಟ್ಟಿ (ಕನಿಷ್ಠ 55%)' },
      { en: 'Ph.D. Admission / Registration Letter', hi: 'पीएचडी प्रवेश / पंजीकरण पत्र', kn: 'ಪಿಎಚ್.ಡಿ ಪ್ರವೇಶ / ನೋಂದಣಿ ಪತ್ರ' },
      { en: 'Aadhaar Linked Bank Account', hi: 'आधार से जुड़ा बैंक खाता', kn: 'ಆಧಾರ್ ಲಿಂಕ್ ಆದ ಬ್ಯಾಂಕ್ ಖಾತೆ' },
    ],
    eligibilityRules: {
      minClass: 'PG',
      maxClass: 'PG',
      maxIncome: null,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: "Prime Minister's Scholarship Scheme for Wards of Ex-Servicemen (PMSS)",
      hi: 'पूर्व सैनिकों के बच्चों के लिए प्रधानमंत्री छात्रवृत्ति योजना (PMSS)',
      kn: 'ಮಾಜಿ ಸೈನಿಕರ ಮಕ್ಕಳಿಗಾಗಿ ಪ್ರಧಾನ ಮಂತ್ರಿ ಸ್ಕಾಲರ್‌ಶಿಪ್ (PMSS)',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-08-01'),
    deadline: new Date('2026-11-15'),
    renewable: true,
    awardAmount: {
      en: '₹3,000/month for Girls, ₹2,500/month for Boys',
      hi: 'छात्राओं के लिए ₹3,000/माह, छात्रों के लिए ₹2,500/माह',
      kn: 'ಹೆಣ್ಣು ಮಕ್ಕಳಿಗೆ ₹3,000/ತಿಂಗಳು, ಗಂಡು ಮಕ್ಕಳಿಗೆ ₹2,500/ತಿಂಗಳು',
    },
    applicationLink: 'https://ksb.gov.in',
    sourceVerifiedLink: 'https://desw.gov.in',
    documentsRequired: [
      { en: 'Ex-Servicemen Discharge Book / ESM Identity Card', hi: 'पूर्व सैनिक डिस्चार्ज बुक / ईएसएम पहचान पत्र', kn: 'ಮಾಜಿ ಸೈನಿಕರ ಡಿಸ್ಚಾರ್ಜ್ ಬುಕ್ / ESM ಗುರುತಿನ ಚೀಟಿ' },
      { en: 'Matriculation / 12th Marksheet (Min 60%)', hi: 'मैट्रिक / 12वीं का अंक पत्र (न्यूनतम 60%)', kn: '10 ನೇ/12 ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ (ಕನಿಷ್ಠ 60%)' },
      { en: 'Bonafide Certificate from College', hi: 'कॉलेज से बोनाफाइड प्रमाण पत्र', kn: 'ಕಾಲೇಜಿನ ಬೋನಾಫೈಡ್ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'PPO Certificate / Dependency Certificate', hi: 'पीपीओ प्रमाण पत्र / निर्भरता प्रमाण पत्र', kn: 'PPO ಪ್ರಮಾಣಪತ್ರ / ಅವಲಂಬಿತ ಪ್ರಮಾಣಪತ್ರ' },
    ],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: null,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'CBSE Single Girl Child Scholarship',
      hi: 'सीबीएसई एकल बालिका छात्रवृत्ति योजना',
      kn: 'ಸಿಬಿಎಸ್‌ಇ ಏಕೈಕ ಹೆಣ್ಣು ಮಗುವಿನ ಸ್ಕಾಲರ್‌ಶಿಪ್',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-09-01'),
    deadline: new Date('2026-12-31'),
    renewable: true,
    awardAmount: {
      en: '₹500/month for 2 years (Class 11 and 12)',
      hi: '2 वर्षों के लिए ₹500/माह (कक्षा 11 और 12)',
      kn: '2 ವರ್ಷಗಳ ಕಾಲ ₹500/ತಿಂಗಳಿಗೆ (11 ಮತ್ತು 12 ನೇ ತರಗತಿ)',
    },
    applicationLink: 'https://cbse.gov.in',
    sourceVerifiedLink: 'https://cbse.gov.in',
    documentsRequired: [
      { en: 'CBSE Class 10 Board Marksheet (Min 60%)', hi: 'सीबीएसई कक्षा 10 बोर्ड अंक पत्र (न्यूनतम 60%)', kn: 'CBSE 10 ನೇ ತರಗತಿಯ ಅಂಕಪಟ್ಟಿ (ಕನಿಷ್ಠ 60%)' },
      { en: 'Single Girl Child Affidavit on Stamp Paper', hi: 'स्टाम्प पेपर पर एकल बालिका हलफनामा', kn: 'ಸ್ಟ್ಯಾಂಪ್ ಪೇಪರ್‌ನಲ್ಲಿ ಏಕೈಕ ಹೆಣ್ಣು ಮಗುವಿನ ಅಫಿಡವಿಟ್' },
      { en: 'CBSE Class 11 School Verification Form', hi: 'सीबीएसई कक्षा 11 स्कूल सत्यापन फॉर्म', kn: 'CBSE 11 ನೇ ತರಗತಿಯ ಶಾಲಾ ಪರಿಶೀಲನಾ ನಮೂನೆ' },
      { en: 'Bank Account Details', hi: 'बैंक खाते का विवरण', kn: 'ಬ್ಯಾಂಕ್ ಖಾತೆಯ ವಿವರಗಳು' },
    ],
    eligibilityRules: {
      minClass: '11th',
      maxClass: '12th',
      maxIncome: null,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['Female'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'Merit-cum-Means Scholarship for Professional and Technical Courses (Minorities)',
      hi: 'पेशेवर और तकनीकी पाठ्यक्रमों के लिए मेरिट-कम-मीन्स छात्रवृत्ति (अल्पसंख्यक)',
      kn: 'ವೃತ್ತಿಪರ ಮತ್ತು ತಾಂತ್ರಿಕ ಕೋರ್ಸ್‌ಗಳಿಗೆ ಮೆರಿಟ್-ಕಮ್-ಮೀನ್ಸ್ ಸ್ಕಾಲರ್‌ಶಿಪ್ (ಅಲ್ಪಸಂಖ್ಯಾತರು)',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: {
      en: 'Course Fee Reimbursement up to ₹20,000/year + Maintenance Allowance',
      hi: 'पाठ्यक्रम शुल्क प्रतिपूर्ति ₹20,000/वर्ष तक + रख-रखाव भत्ता',
      kn: 'ಕೋರ್ಸ್ ಶುಲ್ಕ ಮರುಪಾವತಿ ₹20,000/ವರ್ಷದವರೆಗೆ + ನಿರ್ವಹಣಾ ಭತ್ಯೆ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://minorityaffairs.gov.in',
    documentsRequired: [
      { en: 'Minority Declaration Self-Certificate', hi: 'अल्पसंख्यक घोषणा स्व-प्रमाण पत्र', kn: 'ಅಲ್ಪಸಂಖ್ಯಾತ ಸ್ವಯಂ ಘೋಷಣಾ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Income Certificate (< ₹2.5 Lakh)', hi: 'आय प्रमाण पत्र (< ₹2.5 लाख)', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (< ₹2.5 ಲಕ್ಷ)' },
      { en: 'Previous Exam Marksheet (Min 50%)', hi: 'पिछली परीक्षा का अंक पत्र (न्यूनतम 50%)', kn: 'ಹಿಂದಿನ ಪರೀಕ್ಷೆಯ ಅಂಕಪಟ್ಟಿ (ಕನಿಷ್ಠ 50%)' },
      { en: 'Professional Course Fee Receipt', hi: 'पेशेवर पाठ्यक्रम शुल्क रसीद', kn: 'ವೃತ್ತಿಪರ ಕೋರ್ಸ್ ಶುಲ್ಕ ರಸೀದಿ' },
    ],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['Minority'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'Post-Matric Scholarship for OBC Students',
      hi: 'अन्य पिछड़ा वर्ग (OBC) छात्रों के लिए उत्तर-मैट्रिक छात्रवृत्ति',
      kn: 'ಹಿಂದುಳಿದ ವರ್ಗಗಳ (OBC) ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಮೆಟ್ರಿಕ್ ನಂತರದ ಸ್ಕಾಲರ್‌ಶಿಪ್',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-01'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: {
      en: 'Maintenance Allowance + Mandatory Non-Refundable Fee Coverage',
      hi: 'रख-रखाव भत्ता + अनिवार्य गैर-वापसी योग्य शुल्क कवरेज',
      kn: 'ನಿರ್ವಹಣಾ ಭತ್ಯೆ + ಕಡ್ಡಾಯ ಹಿಂತಿರುಗಿಸಲಾಗದ ಶುಲ್ಕ ಭರಿಸುವಿಕೆ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://socialjustice.gov.in',
    documentsRequired: [
      { en: 'OBC Caste Certificate', hi: 'ओबीसी जाति प्रमाण पत्र', kn: 'OBC ಜಾತಿ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Income Certificate (< ₹2.5 Lakh)', hi: 'आय प्रमाण पत्र (< ₹2.5 लाख)', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (< ₹2.5 ಲಕ್ಷ)' },
      { en: 'Aadhaar Card', hi: 'आधार कार्ड', kn: 'ಆಧಾರ್ ಕಾರ್ಡ್' },
      { en: '10th/12th Marksheet', hi: '10वीं/12वीं का अंक पत्र', kn: '10 ನೇ/12 ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ' },
      { en: 'College Fee Receipt', hi: 'कॉलेज शुल्क रसीद', kn: 'ಕಾಲೇಜು ಶುಲ್ಕ ರಸೀದಿ' },
    ],
    eligibilityRules: {
      minClass: '11th',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['OBC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
  {
    name: {
      en: 'Post-Matric Scholarship for ST Students',
      hi: 'अनुसूचित जनजाति (ST) छात्रों के लिए उत्तर-मैट्रिक छात्रवृत्ति',
      kn: 'ಪರಿಶಿಷ್ಟ ಪಂಗಡ (ST) ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಮೆಟ್ರಿಕ್ ನಂತರದ ಸ್ಕಾಲರ್‌ಶಿಪ್',
    },
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-07-01'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: {
      en: '100% Tuition Fee Reimbursement + Monthly Maintenance Allowance',
      hi: '100% शिक्षण शुल्क प्रतिपूर्ति + मासिक रख-रखाव भत्ता',
      kn: '100% ಟ್ಯೂಷನ್ ಶುಲ್ಕ ಮರುಪಾವತಿ + ಮಾಸಿಕ ನಿರ್ವಹಣಾ ಭತ್ಯೆ',
    },
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://tribal.nic.in',
    documentsRequired: [
      { en: 'ST Tribe Certificate', hi: 'अनुसूचित जनजाति प्रमाण पत्र', kn: 'ಪರಿಶಿಷ್ಟ ಪಂಗಡ ಪ್ರಮಾಣಪತ್ರ' },
      { en: 'Income Certificate (< ₹2.5 Lakh)', hi: 'आय प्रमाण पत्र (< ₹2.5 लाख)', kn: 'ಆದಾಯ ಪ್ರಮಾಣಪತ್ರ (< ₹2.5 ಲಕ್ಷ)' },
      { en: 'Aadhaar Card', hi: 'आधार कार्ड', kn: 'ಆಧಾರ್ ಕಾರ್ಡ್' },
      { en: '10th/12th Marksheet', hi: '10वीं/12वीं का अंक पत्र', kn: '10 ನೇ/12 ನೇ ತರಗತಿ ಅಂಕಪಟ್ಟಿ' },
      { en: 'College Fee Receipt', hi: 'कॉलेज शुल्क रसीद', kn: 'ಕಾಲೇಜು ಶುಲ್ಕ ರಸೀದಿ' },
    ],
    eligibilityRules: {
      minClass: '11th',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['ST'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    featured: false,
  },
];

const seedDatabase = async () => {
  try {
    const connStr = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/scholarconnect';
    console.log(`Connecting to MongoDB at ${connStr}...`);
    await mongoose.connect(connStr);

    console.log('Clearing existing placeholder scholarships collection...');
    await Scholarship.deleteMany({});

    console.log('Seeding 15 verified real Indian government scholarships...');
    const inserted = await Scholarship.insertMany(seedScholarshipsData);

    console.log(`✅ Successfully seeded ${inserted.length} real scholarships into ScholarConnect database!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding scholarships:', error);
    process.exit(1);
  }
};

seedDatabase();
