const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const Scholarship = require('../models/Scholarship');

dotenv.config({ path: path.join(__dirname, '../.env') });

const seedScholarshipsData = [
  {
    name: 'PM Yasasvi Central Sector Scheme for OBC/EWS/EBC Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-01-01'),
    deadline: new Date('2026-09-30'),
    renewable: true,
    awardAmount: '₹75,000 to ₹1,25,000 / year',
    applicationLink: 'https://yet.nta.ac.in',
    sourceVerifiedLink: 'https://socialjustice.gov.in',
    documentsRequired: ['Aadhaar Card', 'Income Certificate (< ₹2.5L)', 'Caste Certificate', 'Class 8/10 Marksheet'],
    eligibilityRules: {
      minClass: '9th',
      maxClass: '12th',
      maxIncome: 250000,
      categories: ['OBC', 'EWS', 'EBC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-15'),
    featured: true,
  },
  {
    name: 'National Means-cum-Merit Scholarship Scheme (NMMSS)',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-02-01'),
    deadline: new Date('2026-10-15'),
    renewable: true,
    awardAmount: '₹12,000 / year',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://dsel.education.gov.in/nmmss',
    documentsRequired: ['Income Certificate (< ₹3.5L)', 'Class 7 Marksheet (Min 55%)', 'Bank Passbook', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: '8th',
      maxClass: '12th',
      maxIncome: 350000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-18'),
    featured: true,
  },
  {
    name: 'Pragati Scholarship Scheme for Girl Students (Degree Technical)',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-03-01'),
    deadline: new Date('2026-11-30'),
    renewable: true,
    awardAmount: '₹50,000 / year',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://www.aicte-india.org/schemes/students-development-schemes/Pragati',
    documentsRequired: ['Bonafide Certificate from College', 'Annual Family Income Certificate (< ₹8L)', 'Class 12 / Diploma Marksheet', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: 800000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['Female'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-20'),
    featured: true,
  },
  {
    name: 'Post-Matric Scholarship for SC Students',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-01-15'),
    deadline: new Date('2026-12-15'),
    renewable: true,
    awardAmount: '100% Tuition Fee Waiver + Monthly Maintenance Allowance',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://socialjustice.gov.in/schemes/26',
    documentsRequired: ['SC Caste Certificate', 'Income Certificate (< ₹2.5L)', 'Fee Receipt of Current Year', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: '11th',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['SC'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-12'),
    featured: true,
  },
  {
    name: 'Pre-Matric Scholarship Scheme for Minority Communities',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-04-01'),
    deadline: new Date('2026-10-31'),
    renewable: true,
    awardAmount: '₹10,000 / year',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://minorityaffairs.gov.in',
    documentsRequired: ['Self-Declaration of Minority Religion', 'Income Certificate (< ₹1L)', 'Previous Class Marksheet (>50%)'],
    eligibilityRules: {
      minClass: '1st',
      maxClass: '10th',
      maxIncome: 100000,
      categories: ['Minority'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-05'),
    featured: false,
  },
  {
    name: 'Rajarshi Chhatrapati Shahu Maharaj Tuition Fee Reimbursement (MahaDBT)',
    issuingBody: 'State Govt',
    state: 'Maharashtra',
    startDate: new Date('2026-02-15'),
    deadline: new Date('2026-08-31'),
    renewable: true,
    awardAmount: '50% to 100% Tuition & Exam Fee Reimbursement',
    applicationLink: 'https://mahadbt.maharashtra.gov.in',
    sourceVerifiedLink: 'https://mahadbt.maharashtra.gov.in/SchemeData/SchemeData?Orientation=V&AppDetailId=1003',
    documentsRequired: ['Maharashtra Domicile Certificate', 'Income Certificate (< ₹8L)', 'CAP Allotment Letter', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'PG',
      maxIncome: 800000,
      categories: ['General', 'EWS', 'OBC'],
      states: ['Maharashtra'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-19'),
    featured: true,
  },
  {
    name: 'Karnataka Vidyasiri Post-Matric Food & Accommodation Maintenance',
    issuingBody: 'State Govt',
    state: 'Karnataka',
    startDate: new Date('2026-03-10'),
    deadline: new Date('2026-09-15'),
    renewable: true,
    awardAmount: '₹15,000 / year Food & Hostel Stipend',
    applicationLink: 'https://ssp.postmatric.karnataka.gov.in',
    sourceVerifiedLink: 'https://bcwd.karnataka.gov.in',
    documentsRequired: ['Karnataka Domicile Certificate', 'Caste & Income Certificate', 'SSLC / PUC Marksheet', 'Ration Card'],
    eligibilityRules: {
      minClass: '11th',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['OBC', 'SC', 'ST'],
      states: ['Karnataka'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-10'),
    featured: false,
  },
  {
    name: 'UP Post-Matric Fee Refund & Scholarship Scheme',
    issuingBody: 'State Govt',
    state: 'Uttar Pradesh',
    startDate: new Date('2026-04-15'),
    deadline: new Date('2026-11-05'),
    renewable: true,
    awardAmount: 'Full Fee Reimbursement + Monthly Living Allowance',
    applicationLink: 'https://scholarship.up.gov.in',
    sourceVerifiedLink: 'https://scholarship.up.gov.in',
    documentsRequired: ['UP Domicile Certificate', 'Income Certificate (< ₹2L)', 'Caste Certificate', 'Fee Receipt'],
    eligibilityRules: {
      minClass: '11th',
      maxClass: 'PG',
      maxIncome: 200000,
      categories: ['ALL'],
      states: ['Uttar Pradesh'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-08'),
    featured: false,
  },
  {
    name: "HDFC Bank Parivartan's ECSS Educational Crisis Scholarship",
    issuingBody: 'Private Trust',
    state: 'ALL',
    startDate: new Date('2026-05-01'),
    deadline: new Date('2026-12-31'),
    renewable: false,
    awardAmount: 'Up to ₹75,000 / year',
    applicationLink: 'https://www.buddy4study.com/page/hdfc-bank-parivartans-ecss-scholarship',
    sourceVerifiedLink: 'https://www.hdfcbank.com/personal/about-us/corporate-social-responsibility',
    documentsRequired: ['Proof of Educational Crisis or Hardship', 'Income Certificate (< ₹6L)', 'Previous Marksheet (>55%)'],
    eligibilityRules: {
      minClass: '1st',
      maxClass: 'PG',
      maxIncome: 600000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-21'),
    featured: true,
  },
  {
    name: 'Reliance Foundation Undergraduate Scholarships',
    issuingBody: 'Private Trust',
    state: 'ALL',
    startDate: new Date('2026-01-01'),
    deadline: new Date('2026-08-15'),
    renewable: true,
    awardAmount: 'Up to ₹2,00,000 over course duration',
    applicationLink: 'https://www.scholarships.reliancefoundation.org',
    sourceVerifiedLink: 'https://www.reliancefoundation.org/education',
    documentsRequired: ['Class 12 Marksheet (>60%)', 'Annual Income Certificate (< ₹15L)', 'Aadhaar Card', 'College Bonafide'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: 1500000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-16'),
    featured: true,
  },
  {
    name: 'Tata Capital Pankh Scholarship Programme',
    issuingBody: 'Private Trust',
    state: 'ALL',
    startDate: new Date('2026-03-01'),
    deadline: new Date('2026-10-01'),
    renewable: true,
    awardAmount: 'Up to 80% of Tuition Fees (Max ₹50,000)',
    applicationLink: 'https://www.tatacapital.com/csr/pankh-scholarship.html',
    sourceVerifiedLink: 'https://www.tatacapital.com/csr.html',
    documentsRequired: ['Photo ID Proof', 'Income Proof (< ₹4L)', 'Marksheet of qualifying exam (>60%)', 'Fee Structure'],
    eligibilityRules: {
      minClass: '6th',
      maxClass: 'UG-4',
      maxIncome: 400000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-14'),
    featured: false,
  },
  {
    name: 'Sitaram Jindal Foundation Merit Scholarship',
    issuingBody: 'Private Trust',
    state: 'ALL',
    startDate: new Date('2026-01-01'),
    deadline: new Date('2026-12-31'),
    renewable: true,
    awardAmount: '₹500 to ₹3,200 / month',
    applicationLink: 'https://www.sitaramjindalfoundation.org/scholarships.php',
    sourceVerifiedLink: 'https://www.sitaramjindalfoundation.org',
    documentsRequired: ['Class 10/12 Marksheet', 'Family Income Certificate (< ₹4L)', 'Certificate of Principal / Dean'],
    eligibilityRules: {
      minClass: '11th',
      maxClass: 'PG',
      maxIncome: 400000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-02'),
    featured: false,
  },
  {
    name: "Prime Minister's Scholarship Scheme for CAPF & AR Personnel",
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-02-01'),
    deadline: new Date('2026-11-15'),
    renewable: true,
    awardAmount: '₹36,000 / year for Girls, ₹30,000 / year for Boys',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://www.warb-mha.gov.in',
    documentsRequired: ['Certificate of Service / Ex-Servicemen PPO', 'Class 12 / Diploma Marksheet (>60%)', 'Bonafide Certificate'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'UG-4',
      maxIncome: null,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-11'),
    featured: false,
  },
  {
    name: 'Central Sector Scheme of Scholarships for College and University Students (CSSS)',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-03-15'),
    deadline: new Date('2026-10-30'),
    renewable: true,
    awardAmount: '₹12,000 to ₹20,000 / year',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://education.gov.in/higher_education',
    documentsRequired: ['Class 12 Board Marksheet (Top 20th Percentile)', 'Income Certificate (< ₹4.5L)', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: 'UG-1',
      maxClass: 'PG',
      maxIncome: 450000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: false,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-17'),
    featured: false,
  },
  {
    name: 'Scholarship for Students with Disabilities (Divyangjan)',
    issuingBody: 'Central Govt',
    state: 'ALL',
    startDate: new Date('2026-01-01'),
    deadline: new Date('2026-12-01'),
    renewable: true,
    awardAmount: '₹14,000 to ₹40,000 / year + Reader Allowance',
    applicationLink: 'https://scholarships.gov.in',
    sourceVerifiedLink: 'https://disabilityaffairs.gov.in',
    documentsRequired: ['Disability Certificate (Min 40%)', 'Income Certificate (< ₹2.5L)', 'Previous Marksheet', 'Aadhaar Card'],
    eligibilityRules: {
      minClass: '9th',
      maxClass: 'PG',
      maxIncome: 250000,
      categories: ['ALL'],
      states: ['ALL'],
      genders: ['ALL'],
      requiresDisability: true,
      requiresFirstGen: false,
      requiresSportsQuota: false,
    },
    isActive: true,
    lastVerifiedDate: new Date('2026-07-21'),
    featured: true,
  },
];

const seedDatabase = async () => {
  try {
    const connStr = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/scholarconnect';
    console.log(`Connecting to MongoDB at ${connStr}...`);
    await mongoose.connect(connStr);

    console.log('Clearing existing scholarships collection...');
    await Scholarship.deleteMany({});

    console.log('Seeding 15 real Indian scholarships...');
    const inserted = await Scholarship.insertMany(seedScholarshipsData);

    console.log(`✅ Successfully seeded ${inserted.length} scholarships into ScholarConnect database!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding scholarships:', error);
    process.exit(1);
  }
};

seedDatabase();
